[package]
name = "grindstone"
version = "0.1.0"
authors = ["Peter Johnston <pemjohns@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"

[dev-dependencies]